apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: spark-jobs
  labels:
    app: minio
    component: object-storage
type: Opaque
stringData:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin123