apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-collector-deployment
  namespace: ingestion
  labels:
    app: binance-collector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binance-collector-deployment
  template:
    metadata:
      labels:
        app: binance-collector-deployment
    spec:
      containers:
      - name: binance-collector
        image: binance-collector:1.0.0
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: MINIO_ACCESS_KEY
          valueFrom: 
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_USER
        - name: MINIO_SECRET_KEY
          valueFrom: 
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_PASSWORD
        - name: MINIO_ENDPOINT
          value: "http://minio.lakehouse.svc.cluster.local:9000"
        - name: MINIO_BUCKET
          value: "datalake"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"